additionalCatalogs:
  minio: |
    connector.name=hive
    hive.metastore.uri=thrift://hive-metastore:9083
    hive.s3.path-style-access=true
    hive.s3.endpoint=http://minio:9000
    hive.s3.aws-access-key=admin
    hive.s3.aws-secret-key=password
    hive.non-managed-table-writes-enabled=true
    hive.storage-format=ORC
    hive.s3.ssl.enabled=false